"use client";
import "./globals.css";
import Script from "next/script";
import { Inter } from "next/font/google";

import { NFTProvider } from "@/context/NFTContext";
import { ThemeProvider } from "../utils/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NFTProvider>
        <body className={`${inter.className} bg-slate-50 dark:bg-[#0d1117]`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="dark:bg-nft-dark bg-white min-h-screen">
              <Navbar />
              <div className="pt-65">{children}</div>
              <Footer />
            </div>
          </ThemeProvider>
        </body>
        <Script
          src="https://kit.fontawesome.com/9d824703d1.js"
          crossorigin="anonymous"
        />
      </NFTProvider>
    </html>
  );
}
