"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./utils/ThemeProvider";
import { ThemeSwitcher } from "./utils/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50 dark:bg-[#0d1117]`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher />
          <div className="dark:bg-nft-dark bg-white min-h-screen">
            <h1>Header</h1>
            {children}
            <h1>Footer</h1>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
